Testing without Cron

diff --git a/templates/Nextcloud/0/docker-compose.yml b/templates/Nextcloud/0/docker-compose.yml
--- a/templates/Nextcloud/0/docker-compose.yml
+++ b/templates/Nextcloud/0/docker-compose.yml
@@ -21,24 +21,24 @@ services:
       traefik.enable: false
     restart: on-failure
   {{- end}}
-  cron:
-    image: nextcloud:fpm-alpine
-    dns: # Using Cloudflare DNS
-      - 1.1.1.1
-      - 1.0.0.1
-    entrypoint: |
-      sh -c 'sh -s <<EOF
-      trap "break;exit" SIGHUP SIGINT SIGTERM
-      while /bin/true; do
-        su -s "/bin/sh" -c "/usr/local/bin/php /var/www/html/cron.php" www-data
-        echo $$(date) - Running cron finished
-        sleep 900
-      done
-      EOF'
-    restart: on-failure
-    user: www-data
-    volumes_from:
-      - nextcloud
+#  cron:
+#    image: nextcloud:fpm-alpine
+#    dns: # Using Cloudflare DNS
+#      - 1.1.1.1
+#      - 1.0.0.1
+#    entrypoint: |
+#      sh -c 'sh -s <<EOF
+#      trap "break;exit" SIGHUP SIGINT SIGTERM
+#      while /bin/true; do
+#        su -s "/bin/sh" -c "/usr/local/bin/php /var/www/html/cron.php" www-data
+#        echo $$(date) - Running cron finished
+#        sleep 900
+#      done
+#      EOF'
+#    restart: on-failure
+#    user: www-data
+#    volumes_from:
+#      - nextcloud
   nextcloud:
     image: nextcloud:fpm-alpine
     dns: # Using Cloudflare DNS
@@ -60,10 +60,10 @@ services:
       {{- if .Values.HOST_LABEL}}
       io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
       {{- end}}
-      io.rancher.sidekicks: cron
+#      io.rancher.sidekicks: cron
       traefik.enable: false
     links:
-      - cron
+#      - cron
       - mysql
       {{- if eq .Values.REDIS "true"}}
       - redis
